panels:
 - name: docs
   height: 100%
   width: 40%
   column: 1
 - name: terminal
   height: 60%
   width: 60%
   column: 2
assets:
 - name: terminal
   method: image
   source: quay.io/openshifthomeroom/workshop-terminal:latest
 - name: content
   method: source
   source: ../../build/site/
 - name: docs
   ports: 10080:10080
   mount_volume_source: ./usr/docs/
   mount_volume_target: ./docs/
   output: quay.io/redhat-gpte/containers-lab:latest
 - name: UI
   ports: 10080:10080
   output: quay.io/redhat-gpte/containers-UI:latest
config:
 - name: setup
   release_version: 1.0
 - name: docs
   git_repo: https://github.com/redhat-scholars/openshift-starter-guides
   branch: main
   create_navigation_page: yes
   labs_only: no
   landing_page: index.adoc
   version: 1.0