config:
 - name: setup
   platform: DESKTOP # accepted values: DESKTOP
 - name: docs
   git_repo: https://github.com/redhat-gpe/ocp4_advanced_deployment.git
   credentials_file: ./git_credentials #optional if repo is public